name: Deploy Supabase Edge Function

on:
  push:
    branches:
      - main # Lub 'master'
    paths:
      - 'supabase/functions/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: latest

      # === NOWY, KLUCZOWY KROK: Ustawienie sekretów ===
      - name: Set Supabase secrets
        run: |
          supabase secrets set --project-ref ${{ secrets.SUPABASE_PROJECT_ID }} SUPABASE_URL=${{ secrets.SUPABASE_URL }}
          supabase secrets set --project-ref ${{ secrets.SUPABASE_PROJECT_ID }} SUPABASE_SERVICE_ROLE_KEY=${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}

      - name: Deploy Edge Function
        run: |
          supabase functions deploy register-client --project-ref ${{ secrets.SUPABASE_PROJECT_ID }} --no-verify-jwt
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
